# Generated by Django 5.0 on 2023-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monetary_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Fixed'), ('V', 'Variable')], max_length=1)),
            ],
        ),
    ]
